server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sparrow?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#
#  security:
#    user:
#      name: root
#      password: 123456

mybatis:
  mapper-locations: classpath:com/sparrow/system/*Mapper.xml
#  type-aliases-package: com.sac.demo.entity
  configuration:
    map-underscore-to-camel-case: true

